version: '3.8'

services:
  ftpserver:
    build: .
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp-data:/var/ftp/pub
    environment:
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: unless-stopped
    container_name: ftp-server

  # Test client for verification
  ftp-test:
    image: alpine:latest
    command: sleep infinity
    depends_on:
      - ftpserver
    volumes:
      - ./test-files:/test-files
    container_name: ftp-test-client